gerenciamento_plusultra/sprint0_pu/planejamento_sprint0.md
gerenciamento_plusultra/sprint0_pu/resultados_sprint0.md
gerenciamento_plusultra/sprint1_pu/planejamento_sprint1.md
gerenciamento_plusultra/sprint1_pu/resultados_sprint1.md
gerenciamento_plusultra/sprint2_pu/planejamento_sprint2.md
gerenciamento_plusultra/sprint2_pu/resultados_sprint2.md
gerenciamento_plusultra/sprint3_pu/planejamento_sprint3.md
gerenciamento_plusultra/sprint3_pu/resultados_sprint3.md
gerenciamento_plusultra/sprint4_pu/planejamento_sprint4.md

Adição da pasta gerencia_plusultra, que contem as documentações das sprints.
Close:
| [#62](https://github.com/fga-eps-mds/2021-1-Bot/issues/62) | Documentação das sprints |
@AmandaNbr

Adicionando a pasta gerencia_plusultra

---

docs/tutoriais/Tutorial_edicao_Rasa.md

Close:
| Issue |         Criar tutorial de rasa em pt para o grupo         |
<!-- 
Descreva os testes que você executou para verificar suas alterações e os detalhes relevantes para sua configuração.
@DouglasMonteles 
@Ericklevy

Modificando o Rasa com o douglas

---

gerencia/EquipePlusUltra/sprint0_pu/planejamento_sprint0.md
gerencia/EquipePlusUltra/sprint0_pu/resultados_sprint0.md
gerencia/EquipePlusUltra/sprint1_pu/planejamento_sprint1.md
gerencia/EquipePlusUltra/sprint1_pu/resultados_sprint1.md
gerencia/EquipePlusUltra/sprint2_pu/planejamento_sprint2.md
gerencia/EquipePlusUltra/sprint2_pu/resultados_sprint2.md
gerencia/EquipePlusUltra/sprint3_pu/planejamento_sprint3.md
gerencia/EquipePlusUltra/sprint3_pu/resultados_sprint3.md
gerencia/EquipePlusUltra/sprint4_pu/planejamento_sprint4.md
gerencia/EquipePlusUltra/sprint4_pu/resultados_sprint4.md

Adicionando a documentação das sprints 0 até 4.
Close:
| [#102](https://github.com/fga-eps-mds/2021-1-Bot/issues/102) | Documentação das sprints 4 e 5 |
@AmandaNbr

Adicionando documentação das sprints

---

.gitignore

adicionado .gitignore, resolve #109

---

docs/tutoriais/Tutorial_edicao_Rasa.md

Close:
| [#numero1](link) | título 1 |
| [#numero2](link) | título 2 |
@fulano
@ciclano

Dev plusultra from docs plusultra

---

docs/plano-de-gerenciamento-de-riscos.md

Adicionando o documento do plano de gerenciamento de riscos.
Close:
| [#105](https://github.com/fga-eps-mds/2021-1-Bot/issues/105) | Plano de gerenciamento de riscos |
@AmandaNbr

📝(#105) Add documento de gerenciamento de riscos

---

docs/CODE_OF_CONDUCT.md

Adicionando informações e tópicos ao código de conduta.
Close:
| [$106](https://github.com/fga-eps-mds/2021-1-Bot/issues/106) | Código de Conduta |
@AmandaNbr

Melhorias no cód. de conduta

---

bot/data/nlu.yml
bot/domain.yml

Melhorei o treinamento para o bot responder se ele é um bot ou um humano (US02)
@DouglasMonteles

🆒(#128): Treinando o bot para responder se ele é um bot

---

docs/tutoriais/Tutorial_Integracao_Rasa_com_Telegram.md

Aos documentos de tutoriais foi adicionado o .MD do tutorial de integração do Rasa com Telegram.
@DouglasMonteles

🔁(#114): Adicionando aos tutoriais o treinamento rasa com telegram

---

README.md

Mais detalhes em #130.
Close:
| #130  | Corrigir guia de instalação no README e outros erros |

📝 adicionado um passo para o levantamento dos conteineres

---

.github/pull_request_template.md

Close:
| #134 | título 1 |
@klmurussi @yudi-azvd

Documentation/(#134) : update template de pr

---

README.md

Foram resolvidos os links quebrados do readme. Nessa mudança também usei caminhos relativos ao invés de links github para os arquivos.
Close:
| #132 | [Bug] Links da parte de contribuição não funcionam |   
- [x ] Você verificou se não há outras [Solicitações de Pull](https://github.com/fga-eps-mds/2021-1-Bot/pulls) para a mesma atualização/alteração?
- [x ] As mudanças seguem as políticas de [commit](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/commits.md) e [branch](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/branches.md)
- [ x] Todos os membros estão de acordo com a atualização
@gatotabaco

:bug:(#132): correcao dos links de como contribuir

---

bot/data/nlu.yml
bot/data/rules.yml
bot/domain.yml

💡(#155): Implementando o fallback do bot

---

docs/canvas.md

Close:
| #103  | Canvas |
@PedroLSF 
@klmurussi

:pencil: [#103] Canvas

---

gerencia/EquipePlusUltra/sprint5_pu/planejamento_sprint5.md
gerencia/EquipePlusUltra/sprint5_pu/resultados_sprint5.md
gerencia/EquipePlusUltra/sprint6_pu/planejamento_sprint6.md

Apagar as checkboxes não marcadas. Poluir menos o template
-->
Adicionando a documentacao das sprints 5 e 6
Close:
| #144  | Fazer documentações da sprint |
@AmandaNbr

📝(#144): Adicionando a documentacao das sprints 5 e 6

---

README.md

Remover papeis dos integrantes.
Close:
| #139  | Arrumar tabela de README |

Documentation(#139)/arrumar tabela readme

---

docs/politicas/branches.md

Close:
| #159 | Alterar nomenclatura da politica de branch |
@LamequeFernandes

Documentation#159/alteracao politica

---

Requisitos do produto

Documento de requisitos do produto, descrevendo as funcionalidades micro do escopo do produto.
Close:
| [#89 ](https://github.com/fga-eps-mds/2021-1-Bot/issues/89) | Elicitação de requisitos |
@AnaCarolinaRodriguesLeite

Create Requisitos do produto

---

docs/plano-de-comunicacao.md

Adicionando o documento de Plano de Comunicação.
Close:
| #143 | Fazer o plano de comunicação |
@AmandaNbr

📝(#143): Adicionando o Plano de Comunicação

---

docs/IdentidadeVisual.md

Faltava a introdução do documento de identidade visual.
Close:
| #55 | Personalidade e Identidade Visual do Bot |
@klmurussi

:pencil: (#55) : introdução

---

gerencia/TimeCapivara/sprint3/results.md

- [ x] Documentação atualizada
Apenas a Issue de documentação da Sprint 3 foi resolvida.
Close:
| #52 | Documentação da Sprint 3 |
- [x ] Você verificou se não há outras [Solicitações de Pull](https://github.com/fga-eps-mds/2021-1-Bot/pulls) para a mesma atualização/alteração?
- [ x] As mudanças seguem as políticas de [commit](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/commits.md) e [branch](https://github.com/fga-eps-mds/2021-1-Bot/blob/docs_capivara/docs/politicas/branches.md)
- [ x] Todos os membros estão de acordo com a atualização
@gatotabaco

📝(#52): documentação sprint 3

---

bot/credentials.yml
bot/data/nlu.yml
bot/data/stories.yml
bot/domain.yml

Foram feitas a maioria das User story da FT03
Close:
| #162  | Adicionando as FT03 |
@DouglasMonteles 
@Ericklevy 
@kayrocesar 
@LamequeFernandes

Feature#162/transmissao e prevencao

---

docs/Requisitos do produto.md

Houve modificações sobre a extensão do arquivo que não estava em .md, alteração do local onde o arquivo estava para a pasta docs, na correção ortográfica e no nome do bot para chatbot.
Close:
| #184  | Elicitação de requisitos |
@AnaCarolinaRodriguesLeite

🐛(#89): correção de extensão

---

gerencia/TimeCapivara/sprint4/planejamento.md
gerencia/TimeCapivara/sprint4/resultados.md
gerencia/TimeCapivara/sprint5/planejamento.md
gerencia/TimeCapivara/sprint5/resultados.md

Gerencia sprint 5
Close:
| #165  | Documentação da sprint 5 |
@gatotabaco

Documentation#165/gerencia sprint5

---

gerencia/TimeCapivara/sprint4/planejamento.md
gerencia/TimeCapivara/sprint4/resultados.md

Documentação de gerencia da sprint 4
Close:
| #53 | Documentação Sprint 4 |
| #numero2 | título 2 |
@gatotabaco

Documentation#53/gerencia sprint4

---

docs/IdentidadeVisual.md

Referências estão fora do padrão ABNT.
Close:
| #194 | Correção no doc de identidade visual  |
@klmurussi

Correção das referências

---

docs/PersonalidadeDoBot.md

Correção das referências no documento e mudança para o padrão dos documentos.
Close:
| #197 | Correção no doc de personalidade-do-bot |
@klmurussi

Correção no doc de personalidade

---

gerencia/TimeCapivara/sprint6/planejamento.md
gerencia/TimeCapivara/sprint6/resultados.md

Documentação da sprint 6
Close:
| #166  | Docuumentação da sprint 6 |
@gatotabaco

Documentation#166/gerencia sprint6

---

docs/documento-de-prototipo.md

Adição do documento de protótipo.
Close:
| #206 | Criar documento do protótipo |
@AmandaNbr

:pencil:(#206): Adicionando o documento de protótipo

---

docs/documento-de-arquitetura.md

A partir do feedback da revisão feita no documento de arquitetura, realizei as mudanças necessárias, fazendo assim alterações nos tópicos:
2. Representação Arquitetural
2.1 Tecnologias
4.2 Descrições de Casos de Uso
5 Visão Lógica
Close:
| #182 | Correção de erros no documento de arquitetura |
@victorear05

Documentation#182/correção documento de arquitetura

---

README.md

Linkado o vídeo para instalação das ferramentas em Windows 10.
Bônus: corrigi algumas palavras e referências para o AlligaBot.
Close:
| #224  |Melhorar README |

:pencil:(#224): linkado o video de instalação de Docker e WSL para Windows 10

---

docs/2021-09-16-faq.md

Adicionado um documento de FAQ para perguntas e problemas frequentes.
Close:
| #218  | Adicionar FAQ |

:pencil:(#218): Adicionado documento de FAQ

---

.github/pull_request_template.md

Adicionando certas informações no template de Pull Request para otimizar o rastreamento e entendimento do que está sendo feito.
Close:
| #219  | Mudar o template de PR |
@AmandaNbr

:repeat:(#219): Adicionando informacoes no template para otimizar os PR's

---

docs/politicas/branches.md

Informações sobre branch develop deletadas.
Close:
| #222  | Alteração na politica de branch |
@LamequeFernandes

:pencil:(#222): prefixo develop deletado

---

docs/documento-de-devops.md

Adicionado no roadmap:
- migração para o jekyll
- automação do deploy da documentação
Close:
| #234  | Atualizar roadmap de devops para a sprint 8 |

:pencil:(#234): atualizado roadmap de devops

---

docs/2021-09-21-dev-docs.md

Adicionado uma breve documentação sobre o container da documentação.
Close:
| #233  | Guia para desenvolvimento e visualização local da documentação |

:pencil:(#233): Adicionado versão inicial do documento que explica como subir o container da documentação

---

docs/documento-de-arquitetura.md

Adição do diagrama de casos de uso, e correção do fluxo de funcionamento.
Close:
| #228| Atualização do documento de arquitetura|
- [] Você verificou se não há outras [Solicitações de Pull](https://github.com/fga-eps-mds/2021-1-Bot/pulls) para a mesma atualização/alteração?
@victorear05

Documentation#228/update doc de arquitetura

---

docs/CONTRIBUTING.md

Houve uma alteração nas orientações para criação de Issue. Na versão anterior o documento dizia que ao criar uma Issue o membro do repositório deveria aguardar a aprovação dela. No lugar disso, foram colocados tópicos referentes a como criar uma issue adequada.
Close:
| #215 | Ajustar a parte de issues no Guia de Contribuição |
|#232 | Atualização do template de issue |
@gatotabaco

🔁(#215): mudança nas orientações para issues

---

docs/fluxo-de-trabalho.md

Adição do documento de fluxo de trabalho
@DouglasMonteles

Documentation#245/fluxo de trabalho

---

gerencia/EquipePlusUltra/sprint8_pu/2021-09-16-planejamento_sprint8.md
gerencia/EquipePlusUltra/sprint8_pu/2021-09-24-resultados_sprint8.md
gerencia/EquipePlusUltra/sprint9_pu/2021-09-24-planejamento_sprint9.md
gerencia/EquipePlusUltra/sprint9_pu/2021-09-24-resultados_sprint9.md

Adição da documentacao das sprints 8 e 9.
Close:
| #243  | Documentação Sprints 8 e 9 |
@AmandaNbr

:pencil:(#243): Adicionando documentacao das sprints 8 e 9

---

README.md
docs/2021-09-16-faq.md

Adicionado link no README para para a seção da FAQ sobre variáveis ambiente. Além disso, foram corrigidos alguns erros ortográficos.
Close:
| #252 | Bug na API do telegram |

:pencil:(#252): adicionado link no README para para a seção da FAQ sobre variáveis ambiente

---

gerencia/GrupoSlowbros/sprint7sb/planejamento-sprint7.md
gerencia/GrupoSlowbros/sprint7sb/resultado-sprint7.md
gerencia/GrupoSlowbros/sprint8sb/planejamento-sprint8.md
gerencia/GrupoSlowbros/sprint8sb/resultado-sprint8.md

Documentação da sprint 7 e 8 da equipe Slowbros
Adição da sprint 7 e 8 ao documento de gerencia.
Close:
| #236  | Documentar sprint 7 e 8 |

Documentação sprints slowbros

---

README.md

Foi incluído ao Readme os vídeos de apresentação da R1 e também adicionei os badges no início.
Close:
| #258  | Adição do video da R1 e inclusão de badges no Readme |
@AnaCarolinaRodriguesLeite

Adição dos vídeos da R1 e inclusão de badges

---

bot/credentials.yml
bot/data/nlu.yml
bot/data/stories.yml
bot/domain.yml

Criação de conversa sobre os cuidados que devem ser tomados no escritório.
Close:
| #247  | Implementação da US26 |

Feature(#247)/us26

---

bot/data/nlu.yml
bot/data/stories.yml
bot/domain.yml

Implementando a US29 a respeito da segurança das vacinas.
Close:
| #257 | Implementação da US29 |
@AmandaNbr 
@PedroLSF

:bulb:(#257): implementada a US29

---

bot/data/nlu.yml
bot/data/stories.yml
bot/domain.yml

Criação de conversa sobre os tipos de máscaras e suas respectivas eficiências.
Close:
| #260| Implementação da US11|

Feature #260/US11

---

bot/data/nlu.yml
bot/data/stories.yml
bot/domain.yml

Criação de conversa sobre o uso correto das máscaras.
Close:
| #262| Implementação da US12|

Feature #262/US12

---

bot/data/nlu.yml
bot/data/stories.yml
bot/domain.yml

Criação de conversa sobre os cuidados no comércio em geral.
Close:
| #264| Implementação da US25|

Feature #264/US25
